english_to_pirate={ 
"Today" : "Tday",
"sailing" : "sailin",
"ocean" : "high seas",
"my" : "me",
"myself" : "meself",
"with" : "wit'",
"friends" : "maties",
"wife" : "lady",
"men" : "lubbers",
"children" : "little sandcrabs",
"are" : "be",
"looking" : "lookin'",
"coins" : "doubloons",
"the" : "th'",
"them" : "'em",
"their" : "they",
"this" : "this here",
"people" : "landlubbers",
"excited" : "'xcited'",
"don't" : "dern't",
"getting" : "gettin'",
"seas" : "briney deep",
"guys" : "scurvey dogs",
"fooled" : "fool'd",
"machinery" : "contraptions",
"find" : "fin'",
"fools" : "scallywags",
"coming" : "comin'",
"cheat" : "hornswaggle",
"found" : "foun'",
"treasure" : "booty",
"lifted" : "lift'd",
"into" : "int'",
"dinner" : "grub",
"cafeteria" : "swill dungeon",
"Everyone" : "E'eryone",
"good" : "jolly ole'",
"drunk" : "grogged",
"took":"pillaged",
"basement" : "bilge",
"rushed" : "rush'd",
"before" : "afore",
"Hey!" : "Ahoy!",
"you" : "ye",
"Damn you" : "ARRRR!",
"pirates" : "buccaneers",
"to" : "ta",
"turned" : "turn'd"
}
